### ISSUE TITLE
Build Error: pow10f is not declared

### ISSUE THREAD

**Issue by Momomentum** [x42/jack-ir#1]
When I try to build jack-ir, I get the following error message:
`jack-ir.cc:305:21: error: ‘pow10f’ was not declared in this scope; did you mean ‘powf’?`

From pow10 man entry:
```
Note well: These functions perform exactly the same task as the
functions described in exp10(3), with the difference that the latter
functions are now standardized in TS 18661-4:2015.  Those latter
functions should be used in preference to the functions described in
this page.
```
I replaced pow10f with exp10f and it now builds. Should I submit a pull request?

**Comment by x42** [comment]
Thanks for the heads up. It was trivial enough to fix, no need for a pull request.
